### ISSUE TITLE
Allow control if a card is played open or closed

### ISSUE THREAD

**Issue by raatmarien** [raatmarien/playcardswith.me#141]
Currently when a card is played it is played open if it was put in the deck open and closed if it was put in the deck closed. However in a lot of games you just want to play cards open, otherwise you would have kept them in your deck. But in some rare cases I can imagine cards needing to be played closed. For example when you want to pass cards secretly to another player, like at the start of Hearts (hartenjagen).

So I see the need for the ability to choose how the card is played in a real way, right now the behavior is kind of random and rarely what you expect.

(1) One option could be to always play the cards closed, however I think this would get annoying quite fast in most games, since you then need to play the card and click it to open it afterwards.

(2) Another option would be to have an option on your own hand to decide if you want to play cards open or closed (maybe a switch like UI?). But we of course want as little UI as possible, and if you hide it people might not find it when we need it.

(3) Another option I see would be to allow players to turn cards in their hand. A card would automatically turn open when it enters their hand and they could turn it by clicking it. Then when they play it, the card would be open if it was open in the hand and closed if it was closed in the hand.

(4) A last option would be to display a message like "Press <space> to play this card closed" when a card is dragged out of the hand. Then when they press space it is turned over and the card can be played closed. However, how would this work when players don't have a keyboard? You could show an alternative like "Tap here while holding the card to turn it over", but that seems a bit hard. You could also say that advanced features like playing cards closed are for computer users only, but that would of course be a limitation

**Comment by raatmarien** [comment]
I think option (3) might be best. What do you think of these options or do you know another option? I would appreciate your input @flori9 @sambeard @jchmrt

**Comment by flori9** [comment]
I also think option (3) would be best. That also gives the least surprises; the state of a card stays the same as when you're dragging it.

Maybe we could add some advanced options later for power users to customize this? With option 3 the main option I could imagine is "always play closed". Instead of setting that per player I think making it global would be fine, as it mainly depends on which you're playing. But that has a low priority.

A fancy (very low priority) option could be to create some sort of "inbox" where you can drag cards that are meant for another player, as there are more games that involve passing cards. Then it's also fully clear for which player the cards are. This is probably better than allowing players to directly drag cards into another hand, at least for Hearts. If implemented, that should probably be optional.

By the way, to make options like these discoverable, we could maybe add some presets for popular games on the main page (probably below the fold). These presets would influence the deck used, default deal size and options. This could also help a bit with SEO. :P

**Comment by jchmrt** [comment]
Yeah, I guess option 3 is best.

**Comment by raatmarien** [comment]
Okay, I will try to implement option (3) then.
