### ISSUE TITLE
Warning about findDOMNode in console

### ISSUE THREAD

**Issue by raatmarien** [raatmarien/playcardswith.me#56]
```index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Draggable which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (at CardComponent.tsx:104)
    in DraggableCore (created by Draggable)
    in Draggable (at CardComponent.tsx:91)
    in div (at CardComponent.tsx:90)
    in CardComponent (at TableComponent.tsx:23)
    in div (at TableComponent.tsx:17)
    in TableComponent (at App.tsx:67)
    in div (at App.tsx:65)
    in App (at src/index.tsx:9)
    in StrictMode (at src/index.tsx:8)```

**Comment by FredrikAugust** [comment]
Hello! Saw this issue, and thought I'd share some insight as I've encountered this before.

Long story short, there's nothing you can do to fix this except either stop using `react-draggable`, or forking `react-draggable` and reworking it to not use `findDomNode`.

The reason you're getting this warning is because you're using the new `React.StrictMode`, which is warning you about the [deprecation of `findDomNode`](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage).

There is an [issue opened up at `react-draggable` which addresses this](https://github.com/STRML/react-draggable/issues/440), but no action has been taken yet (not even a dev response).

The best thing you can do is probably wait for them to fix this, as for now, it appears it still works, it just gives you a warning during development.

**Comment by raatmarien** [comment]
Thanks for your detailed explanation Frederik! I think you are right and waiting is the best solution. Maybe there is a possibility to suppress or hide this warning, but I'd have no idea how.

**Comment by FredrikAugust** [comment]
No problem!

As for suppressing the error; I think the only way of doing this is by not using _strict mode_, but then you lose the benefits of strict mode, so it's a matter of priority. If it's any consolidation, the warning isn't printed in production :)

**Comment by raatmarien** [comment]
Ah, that it isn't shown in production is a lot better already, good to know. I will close the issue then :)
