### ISSUE TITLE
Make dragging cards from the deck directly to your hand (and the other way around) possible

### ISSUE THREAD

**Issue by flori9** [raatmarien/playcardswith.me#76]
Right now, this doesn't work.
(whether backend changes are needed depends on the implementation)

**Comment by raatmarien** [comment]
Correct, the problem is that right now the draggable implementation differs for deck, table and hand cards. We could implement all the dragStops with handlers to send the right message in all of them, but this is quite some work and quite ugly. To really fix it, we need to abstract away this part of the draggable code into a shared component. Maybe in CardComponent... Hard part is that there are real differences in how the different card components should handle being dragged...

**Comment by raatmarien** [comment]
I don't think backend changes will be needed
